spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gpt
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  profiles:
    active: multiflex-chatgpt-local

openai:
  url:
    model: https://api.openai.com/v1/models
    model-list: https://api.openai.com/v1/models/
    legacy-prompt: https://api.openai.com/v1/completions
    prompt: https://api.openai.com/v1/chat/completions